Feature 1
fernando-silvabr66/Hello-Microverse pull request #1
Opened 2022-01-06 18:10 UTC by fernando-silvabr66

2022-01-06 19:30 UTC, HENRYKC24 requested changes
# STATUS: CHANGES REQUESTED :recycle: 
![Change requested](https://media.giphy.com/media/JoxvmZFZ224I4kD8qN/giphy.gif)
Hi @fernando-silvabr66 :wave:
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] You did a good job but I think you forgot to add a pull request summary. Adding a good pull request summary tells the reviewer more about the pull request and what to expect. This makes the work easy for everyone and appear very professional.
![image](https://user-images.githubusercontent.com/45668340/148437105-d7e9c96f-a583-499b-871c-a0f12db7cf73.png)
You can [read this](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/) for more information.

- [ ] While you made a frantic effort to make sure you use GitHub Flow, you seemingly forgot to make your branch name descriptive.
![image](https://user-images.githubusercontent.com/45668340/148438919-267145e8-7540-4af1-b0a4-c60524b98973.png)
For example, you can call the branch `created-hello-microverse-project`
Just a descriptive name that would make it clear what the branch is all about. [Read this](https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/) for more information on **how to rename a local and remote git branch**.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 19:30 UTC, HENRYKC24 commented on .github/workflows/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
This is great:+1: You used the correct linter config file. Keep that up:clap:

2022-01-06 21:54 UTC, Whoistolu requested changes
Hi @fernando-silvabr66 ,

Good job so far implementing some of the recommended changes by the previous reviewer however, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] [REQUIRED] It will be nice to make your branch name descriptive as recommended by the previous reviewer,  you can actually edit the branch name. Just a descriptive name that would make it clear what the branch is all about (e.g. 'created_sidebar' or 'added_comments_section'). Kindly refer to [this link](https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/) for more guidance.
![img](https://user-images.githubusercontent.com/58692590/148456875-e5cce86f-a946-49d0-8988-5d57ba8d7ed5.png)

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-07 10:23 UTC, closed without merging

2022-01-07 10:50 UTC, fernando-silvabr66 commented
Hi Tolu,

This is my Week 1 in Microverse Program and I´m a little bit confused with
Github.

Let me try to put my points:

1- When I received the 1st PR comment (from @HenryKC24) I tried to change
the branch name as requested (and following the steps I received in the
Code Review feedback), but it occurs that Github closed the #1 PR and ask
me to make a new PR (wich is not recommended by the Code Review process).
So, first I tried creating a new PR but it was to keep the 1st PR
(which does not occur) and Github created a new (#2) PR, then I tried to
keep only the 1st, etc.

2- After your review, I went to Github again and found a way to rename the
branch (within Github), but the same close/ask for a new PR occurs.

3- If you go to my Hello-Microverse right now you can see that the branch
name is changed, but the Pull Requests are with 'closed' status, as you can
see below.
[image: image.png]
[image: image.png]
I mean, I don´t know how to fix it once it is an automatic Github process
(When renaming a branch it closes the PR and asks for a new one).

Please, what should I do in this case?

Regards,
Fernando.



On Thu, Jan 6, 2022 at 6:54 PM Ajise Toluwase ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @fernando-silvabr66 <https://github.com/fernando-silvabr66> ,
>
> Good job so far implementing some of the recommended changes by the
> previous reviewer however, there are some issues that you still need to
> work on to go to the next project but you are almost there!
> Required Changes ♻️
>
>    - [REQUIRED] It will be nice to make your branch name descriptive as
>    recommended by the previous reviewer. Just a descriptive name that would
>    make it clear what the branch is all about (e.g. 'created_sidebar' or
>    'added_comments_section'). Kindly refer to this link
>    <https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/>
>    for more guidance.
>    [image: img]
>    <https://user-images.githubusercontent.com/58692590/148456875-e5cce86f-a946-49d0-8988-5d57ba8d7ed5.png>
>
> *Check the inline comments under the review for sections to improve.*
>
> Cheers and Happy coding!
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fernando-silvabr66/Hello-Microverse/pull/1#pullrequestreview-846104039>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASS42YYTSMOCPYV5Y6R2U5DUUYFTFANCNFSM5LM44DIQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-07 10:58 UTC, fernando-silvabr66 commented
beloe are the images I mentioned:

![image](https://user-images.githubusercontent.com/77974883/148534281-754fed9d-647f-4a91-9e8f-568d6c14eccf.png)

![image](https://user-images.githubusercontent.com/77974883/148534073-dc467097-c37b-475c-bb15-2d5ce815b564.png)

2022-01-07 13:51 UTC, Whoistolu commented
Hello @fernando-silvabr66 ,
I am sorry about how you feel. Let me..

2022-01-07 14:15 UTC, mke2111 reviewed
Hey @fernando-silvabr66,

Yes, this happens once you try to rename a branch. You always have to keep in mind to create meaningful branch names right from the start, or before you create a PR. 

@HENRYKC24 was meant to invalidate this PR right from the start since the branch name should have the name of the feature implemented.
Since he did not invalidate the PR, @Whoistolu  was meant to approve this PR if that was the only issue that was left to fix.

The next step is to create a new 'meaningful' branch and then a new PR and in this new PR, remember to link this old PR so that the next reviewer can APPROVE.

Thank you @Whoistolu for helping here.

> NOTE Next reviewer, Please approve this PR.

2022-01-07 14:21 UTC, Whoistolu commented
Thank you for a swift response @mke2111.

@fernando-silvabr66 Apologies concerning this.

Kindly follow the steps stated above by @mke2111 and your project will be approved.
Happy coding!!!

2022-01-07 14:44 UTC, HENRYKC24 commented
Noted @mke2111. I will definitely invalidate the next time this happens. Thank you very much for the clarification and support:pray: